POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "",
  "number": "123"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Missing Number"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "000-000"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "999-999"
}